constants:  # constants have a value that never changes
  GENESIS_SLOT:
    type: uint64
    constant: 0
  GENESIS_EPOCH:
    type: uint64
    constant: 0
  FAR_FUTURE_EPOCH:
    type: uint64
    constant: 1099511627776
  BASE_REWARDS_PER_EPOCH:
    type: uint64
  DEPOSIT_CONTRACT_TREE_DEPTH:
    type: uint64
    constant: 32
  JUSTIFICATION_BITS_LENGTH:
    type: uint64
    constant: 4
  ENDIANNESS:
    type: string
    constant: little
configurables:  # config keys are grouped by fork, but must be unique across all forks
  phase0:
    MAX_COMMITTEES_PER_SLOT:                              uint64
    TARGET_COMMITTEE_SIZE:                                uint64
    MAX_VALIDATORS_PER_COMMITTEE:                         uint64
    MIN_PER_EPOCH_CHURN_LIMIT:                            uint64
    CHURN_LIMIT_QUOTIENT:                                 uint64
    SHUFFLE_ROUND_COUNT:                                  uint64
    MIN_GENESIS_ACTIVE_VALIDATOR_COUNT:                   uint64
    MIN_GENESIS_TIME:                                     uint64
    HYSTERESIS_QUOTIENT:                                  uint64
    HYSTERESIS_DOWNWARD_MULTIPLIER:                       uint64
    HYSTERESIS_UPWARD_MULTIPLIER:                         uint64
    PROPORTIONAL_SLASHING_MULTIPLIER:                     uint64
    SAFE_SLOTS_TO_UPDATE_JUSTIFIED:                       uint64
    ETH1_FOLLOW_DISTANCE:                                 uint64
    TARGET_AGGREGATORS_PER_COMMITTEE:                     uint64
    RANDOM_SUBNETS_PER_VALIDATOR:                         uint64
    EPOCHS_PER_RANDOM_SUBNET_SUBSCRIPTION:                uint64
    SECONDS_PER_ETH1_BLOCK:                               uint64
    DEPOSIT_CHAIN_ID:                                     uint64
    DEPOSIT_NETWORK_ID:                                   uint64
    DEPOSIT_CONTRACT_ADDRESS:                             uint64
    MIN_DEPOSIT_AMOUNT:                                   uint64
    MAX_EFFECTIVE_BALANCE:                                uint64
    EJECTION_BALANCE:                                     uint64
    EFFECTIVE_BALANCE_INCREMENT:                          uint64
    GENESIS_FORK_VERSION:                                 uint64
    BLS_WITHDRAWAL_PREFIX:                                uint64
    GENESIS_DELAY:                                        uint64
    SECONDS_PER_SLOT:                                     uint64
    MIN_ATTESTATION_INCLUSION_DELAY:                      uint64
    SLOTS_PER_EPOCH:                                      uint64
    MIN_SEED_LOOKAHEAD:                                   uint64
    MAX_SEED_LOOKAHEAD:                                   uint64
    EPOCHS_PER_ETH1_VOTING_PERIOD:                        uint64
    SLOTS_PER_HISTORICAL_ROOT:                            uint64
    MIN_VALIDATOR_WITHDRAWABILITY_DELAY:                  uint64
    SHARD_COMMITTEE_PERIOD:                               uint64
    MAX_EPOCHS_PER_CROSSLINK:                             uint64
    MIN_EPOCHS_TO_INACTIVITY_PENALTY:                     uint64
    EPOCHS_PER_HISTORICAL_VECTOR:                         uint64
    EPOCHS_PER_SLASHINGS_VECTOR:                          uint64
    HISTORICAL_ROOTS_LIMIT:                               uint64
    VALIDATOR_REGISTRY_LIMIT:                             uint64
    BASE_REWARD_FACTOR:                                   uint64
    WHISTLEBLOWER_REWARD_QUOTIENT:                        uint64
    PROPOSER_REWARD_QUOTIENT:                             uint64
    INACTIVITY_PENALTY_QUOTIENT:                          uint64
    MIN_SLASHING_PENALTY_QUOTIENT:                        uint64
    MAX_PROPOSER_SLASHINGS:                               uint64
    MAX_ATTESTER_SLASHINGS:                               uint64
    MAX_ATTESTATIONS:                                     uint64
    MAX_DEPOSITS:                                         uint64
    MAX_VOLUNTARY_EXITS:                                  uint64
    DOMAIN_BEACON_PROPOSER:                               uint64
    DOMAIN_BEACON_ATTESTER:                               uint64
    DOMAIN_RANDAO:                                        uint64
    DOMAIN_DEPOSIT:                                       uint64
    DOMAIN_VOLUNTARY_EXIT:                                uint64
    DOMAIN_SELECTION_PROOF:                               uint64
    DOMAIN_AGGREGATE_AND_PROOF:                           uint64
  phase1:
    PHASE_1_FORK_VERSION:                                 uint64
    PHASE_1_FORK_SLOT:                                    uint64
    INITIAL_ACTIVE_SHARDS:                                uint64
    MAX_SHARDS:                                           uint64
    LIGHT_CLIENT_COMMITTEE_SIZE:                          uint64
    GASPRICE_ADJUSTMENT_COEFFICIENT:                      uint64
    MAX_SHARD_BLOCK_SIZE:                                 uint64
    TARGET_SHARD_BLOCK_SIZE:                              uint64
    SHARD_BLOCK_OFFSETS:                                  uint64
    MAX_SHARD_BLOCKS_PER_ATTESTATION:                     uint64
    BYTES_PER_CUSTODY_CHUNK:                              uint64
    CUSTODY_RESPONSE_DEPTH:                               uint64
    MAX_GASPRICE:                                         uint64
    MIN_GASPRICE:                                         uint64
    ONLINE_PERIOD:                                        uint64
    LIGHT_CLIENT_COMMITTEE_PERIOD:                        uint64
    MAX_CUSTODY_CHUNK_CHALLENGE_RECORDS:                  uint64
    DOMAIN_SHARD_PROPOSAL:                                uint64
    DOMAIN_SHARD_COMMITTEE:                               uint64
    DOMAIN_LIGHT_CLIENT:                                  uint64
    DOMAIN_CUSTODY_BIT_SLASHING:                          uint64
    DOMAIN_LIGHT_SELECTION_PROOF:                         uint64
    DOMAIN_LIGHT_AGGREGATE_AND_PROOF:                     uint64
    RANDAO_PENALTY_EPOCHS:                                uint64
    EARLY_DERIVED_SECRET_PENALTY_MAX_FUTURE_EPOCHS:       uint64
    EPOCHS_PER_CUSTODY_PERIOD:                            uint64
    CUSTODY_PERIOD_TO_RANDAO_PADDING:                     uint64
    MAX_CHUNK_CHALLENGE_DELAY:                            uint64
    CUSTODY_PRIME:                                        uint64
    CUSTODY_SECRETS:                                      uint64
    BYTES_PER_CUSTODY_ATOM:                               uint64
    CUSTODY_PROBABILITY_EXPONENT:                         uint64
    MAX_CUSTODY_KEY_REVEALS:                              uint64
    MAX_EARLY_DERIVED_SECRET_REVEALS:                     uint64
    MAX_CUSTODY_CHUNK_CHALLENGES:                         uint64
    MAX_CUSTODY_CHUNK_CHALLENGE_RESP:                     uint64
    MAX_CUSTODY_SLASHINGS:                                uint64
    EARLY_DERIVED_SECRET_REVEAL_SLOT_REWARD_MULTIPLE:     uint64
    MINOR_REWARD_QUOTIENT:                                uint64
